INSERT INTO Survivors VALUES('Ace Visconti','Open-Handed','Up the Ante','Ace in the Hole','I have seen a poor new soul in this nightmare. For most of the others trapped here, fear is our common denominator. This man does not follow suit. Instead, he stands defiantly, analyzing his surroundings with an eerie confidence. In the mere glimpses of him I could afford, I saw a crooked smile as he scavenged something on the ground. Just by watching him from afar, I felt him ignite a fleeting spark of hope in my heart just before he melted into the shadows. With the remaining conviction I have left, I do pray that good fortune stays on his side.

','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3e/New_Store_Ace.png/revision/latest?cb=20220325045215');
INSERT INTO Survivors VALUES('Ada Wong','Wiretap','Reactive Healing','Low Profile','Sometimes it’s safer to keep people guessing, and no one knows this better than Ada Wong. Dexterous and enigmatic, Ada’s survival skills make her a valuable ally, provided interests remain aligned.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d3/New_Store_Ada.png/revision/latest?cb=20220830161534');
INSERT INTO Survivors VALUES('Adam Francis','Diversion','Deliverance','Autodidact','The clever and selfless Adam Francis is no stranger to heroism, boldly risking his own life to save others. A dependable leader in the face of danger, Adam’s ability to strategize quickly has been known to pay off, even if it means putting himself in harm’s way.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/05/New_Store_Adam.png/revision/latest?cb=20220325045225');
INSERT INTO Survivors VALUES('Ash Williams','Flip-Flop','Buckle Up','Mettle of Man','Though he proudly identifies as a self-described “alone wolf,” Ash’s shockingly high pain tolerance and scathing wit have proven invaluable in the face of supernatural danger. Those wheels are always turning, even when the situation appears dire. Never underestimate his mettle.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/43/New_Store_Ash.png/revision/latest?cb=20220325045235');
INSERT INTO Survivors VALUES('Cheryl Mason','Soul Guard','Blood Pact','Repressed Alliance','No stranger to indescribable terror, Cheryl Mason has grown emboldened by the looming presence of evil. Drawing strength from the horrors of her past, she has learned to manipulate powers from beyond to achieve her noble goal.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/78/New_Store_Cheryl.png/revision/latest?cb=20220325045254');
INSERT INTO Survivors VALUES('Claudette Morel','Empathy','Botany Knowledge','Self-Care','Claudette understands the value of altruism, using her aptitude for botany to ensure her teammates are prepared for the challenges ahead. An expert healer to herself and others, Claudette’s supportive presence is always welcome.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3f/New_Store_Claudette.png/revision/latest?cb=20220325045338');
INSERT INTO Survivors VALUES('David King','We''re Gonna Live Forever','Dead Hard','No Mither','Another man. In this arena I guess I could start to label as “home”. A man with an athletic frame. He carries an impressive stature. He seems untouchable at first glance. But a second look tells me something else. He seems torn. Distraught and broken. Maybe not by body, but by mind. I have seen him outrun the creatures. But also on a hook, with his bowels fleeing his torso. Something unsettling about that sight.


','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/New_Store_David.png/revision/latest?cb=20220325045347');
INSERT INTO Survivors VALUES('David Tapp','Tenacity','Detective''s Hunch','Stake Out','I am not a stranger to law enforcement professionals. I have learned to…spot them. To recognize their posture and sway. Now, one seems to inhabit this, my new home. He looks worn down, but just like me, he refuses to simply lay down and await the coming pain and death. The struggle is the only thing that keeps him sane – something to focus on. Just as you can recognize the hardship of a law enforcer, many times you can also spot a man that has experienced what others never come near. Beatings and violence, determination. Maybe this new man seeks justice? Maybe he still carries a badge? Whatever might he be looking for here, at this place that lacks justice or an end?


','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/71/New_Store_Tapp.png/revision/latest?cb=20220325045550');
INSERT INTO Survivors VALUES('Dwight Fairfield','Bond','Prove Thyself','Leader','An unlikely leader forced to rise to the occasion, Dwight Fairfield’s reluctant bravery inspires those around him. Understanding the value of teamwork, Dwight is adept at locating and bolstering the efficiency of his teammates.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5c/New_Store_Dwight.png/revision/latest?cb=20220325045357');
INSERT INTO Survivors VALUES('Felix Richter','Visionary','Desperate Measures','Built to Last','Often called a visionary for his brilliant architectural work, Felix Richter is as determined as he is debonair. Capable of operating at heightened efficiency under immense pressure, his expertise has proven invaluable – especially when facing a deadline.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/88/New_Store_Felix.png/revision/latest?cb=20220621144237');
INSERT INTO Survivors VALUES('Feng Min','Technician','Lithe','Alert','A young woman surprised me the other day. She is another guest in this nightmare I can not seem to wake up from. She came running, passed by a wounded girl and didn’t stop. Just a glance behind her, and she was off again. With a determined look on her face, like she had something important to do. A lone wolf maybe? I am not sure what I should call this new person.


','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d9/New_Store_Feng.png/revision/latest?cb=20220325045426');
INSERT INTO Survivors VALUES('Haddie Kaur','Inner Focus','Residual Manifest','Overzealous','Plagued by chilling visions of the inexplicable, Haddie Kaur is driven to brave the perils of the unknown. Possessing the ability to see realms beyond our own, she knows more about the encroaching darkness than most. Perhaps that’s why she’s not afraid to stand face-to-face with danger with flashlight in hand.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/65/New_Store_Haddie.png/revision/latest?cb=20220607191731');
INSERT INTO Survivors VALUES('Jake Park','Iron Will','Calm Spirit','Saboteur','A solitary specialist, Jake Park’s time in the wilderness has sharpened his survival instincts. Stealthy and resourceful, the only sign of his presence are the Sabotaged Hooks he leaves behind.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/04/New_Store_Jake.png/revision/latest?cb=20220325045435');
INSERT INTO Survivors VALUES('Jane Romero','Solidarity','Poised','Head On','Celebrity status never changed Jane Romero, who always preferred to tackle a challenge head on. Blessed with a problem-solver''s intuition, her aptitude for working with others is a valued asset. Though words are always her first choice, she’s certainly not afraid to get her hands dirty.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f4/New_Store_Jane.png/revision/latest?cb=20220325045446');
INSERT INTO Survivors VALUES('Jeff Johansen','Breakdown','Aftercare','Distortion','With a reserved nature often mistaken for stoicism, Jeff Johansen found solace in artistic expression. A simple man with a strong appreciation for home-brewed beer and heavy metal, he’s learned to live with the darkness of his past, holding steadfast in the face of adversity.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7d/New_Store_Jeff.png/revision/latest?cb=20220325045454');
INSERT INTO Survivors VALUES('Jill Valentine','Counterforce','Resurgence','Blast Mine','Bravery comes natural to Jill Valentine, whose heroism proved invaluable during her harrowing time in Raccoon City. Even with a lethal pursuer on her trail, Jill’s survival instincts provide her and her teammates with a few crucial advantages. Don’t expect her to go down without a fight.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fb/New_Store_Jill.png/revision/latest?cb=20220618144709');
INSERT INTO Survivors VALUES('Jonah Vasquez','Overcome','Corrective Action','Boon: Exponential','Jonah Vasquez can tell you first-hand that there’s strength in numbers – literally. A seasoned codebreaker and master of mathematics, Jonah’s logical mind makes for a key addition to any team, multiplying chances of successful teamwork by an exponential degree.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/07/New_Store_Jonah.png/revision/latest?cb=20220618144723');
INSERT INTO Survivors VALUES('Kate Denson','Dance With Me','Windows of Opportunity','Boil Over','A ray of sunshine illuminated this cold and gray place - a ray in the form of a woman. I heard her before I saw her, a voice, more beautiful than I had encountered in some time, came drifting through the trees. While a lament might have been more suited to this sepulchral locale, she sang a song of joy, of hope and family. Her warm smile greeted any that joined her at the campfire and, just for moment, they were able to forget which realm they inhabited.
As quick as she was to make friends, I got the feeling that to cross her would be a mistake. To remain so positive and upbeat in such a place would require a will of iron. Perhaps less a ray of sunshine then, but a bolt of lightning? Brilliant light and great power that could split the world in two.''''

','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/New_Store_Kate.png/revision/latest?cb=20220325045505');
INSERT INTO Survivors VALUES('Laurie Strode','Sole Survivor','Object of Obsession','Decisive Strike','I stumbled upon another soul in this doomed corner of the earth.I do not know her name, but there is something about her.I have never crossed paths with her, but she seems as if she''s been doing this for far too long.Weary of the environment, clad in a kind of controlled panic, constantly looking over her shoulder, on the lookout.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/90/New_Store_Laurie.png/revision/latest?cb=20220325045515');
INSERT INTO Survivors VALUES('Leon Scott Kennedy','Bite the Bullet','Flashbang','Rookie Spirit','Leon Kennedy might be a Rookie, but during that one fateful night, he faced an entire lifetime of horror and brutality. At once resilient and resourceful, Leon is adaptable above all, whether crafting makeshift weaponry or retracing his steps through labyrinthine hallways.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b3/New_Store_Leon.png/revision/latest?cb=20220618144716');
INSERT INTO Survivors VALUES('Meg Thomas','Quick & Quiet','Sprint Burst','Adrenaline','Driven by reckless courage, the athletic Meg Thomas has never been afraid to push her limits. Prone to stepping up in the clutch, Meg gets a thrill out of goading Killers into lengthy chases, buying essential time for her teammates.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c8/New_Store_Meg.png/revision/latest?cb=20220325045523');
INSERT INTO Survivors VALUES('Mikaela Reid','Clairvoyance','Boon: Circle of Healing','Boon: Shadow Step','A passion for the mystic arts has proven invaluable for Mikaela Reid. A proud horror aficionado and admirer of the macabre, her supernatural touch has opened the door to new possibilities. Though some were initially wary, teammates quickly took to her alternative methods upon seeing the results.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ed/New_Store_Mikaela.png/revision/latest?cb=20220618144730');
INSERT INTO Survivors VALUES('Nancy Wheeler','Better Together','Fixated','Inner Strength','Studious and rebellious, Nancy Wheeler is a stubborn investigator with an instinct for a good story. When her closest friend, Barb went missing, she did everything she could to unravel the truth and secure justice. A brilliant journalist, she chases stories and follows leads despite the inequality and chauvinism she encounters at the workplace. Pursuing a lead one evening, she fearlessly approaches the Hawkins National Laboratory before suddenly losing consciousness. A moment later she awakens in a strange misty realm with the sound of a familiar roar echoing through the air.','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1e/New_Store_Nancy.png/revision/latest?cb=20220618144446');
INSERT INTO Survivors VALUES('Nea Karlsson','Balanced Landing','Urban Evasion','Streetwise','At first sight I thought it was a cat that passed me by, just a few meters behind me. A shadow that moved without sound. But yelling is not wise in this place. I have spotted her more times, but just in the peripheral. I still don’t know her name, but she evades the monsters with a certain grace. 
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/ba/New_Store_Nea.png/revision/latest?cb=20220325045534');
INSERT INTO Survivors VALUES('Quentin Smith','Wake Up!','Pharmacy','Vigil','“I saw a young man the other day. He seemed both awake and asleep at the same time. A bit drowsy, but determined. Even though I lacked to see anyone or anything going after him, he would not stop. I have witnessed true fear many times at this place. But this man provides a whole new spectra of fear. What would make a man too afraid to even stop to take a breath? He seems determined to reach the gates. I too had that urge once. But I failed too many times to reach them, too many mistakes and deaths. But this young man is different. Maybe he will actually escape. For real. But he looks tired, so intensely tired.”
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/New_Store_Quentin.png/revision/latest?cb=20220325045543');
INSERT INTO Survivors VALUES('Rebecca Chambers','Better than New','Reassurance','Hyperfocus','Never underestimate the value of an experienced field medic. Rebecca Chambers leads by example when almost all seems lost, sometimes facing grave danger to assist her allies. Her medical brilliance keeps teammates alive and inspired, even if it puts her own safety at risk.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/New_Store_Rebecca.png/revision/latest?cb=20220830161525');
INSERT INTO Survivors VALUES('Steve Harrington','Babysitter','Camaraderie','Second Wind','Popular and arrogant, yet compassionate, Steve Harrington is an unlikely mentor and leader. He often acts as a surrogate big brother to a younger boy named Dustin. He even helped him find his slimy inter-dimensional pet Demogorgon, D''Artagnan. His reputation as a protector grew and he soon became a sort of "babysitter" for a group of kids in Hawkins with a knack for messing around with strange and dangerous things. His courage is unmatched so that he was even able to fend off a Demogorgon when it threatened his friends. One evening he received a call for assistance from his friend Nancy Wheeler. He drove all the way to the Hawkins National Laboratory to see if she was okay. He searched the area but only found her notebook. Before he realised what was happening the ground opened up and a swirl of black mist filled his eyes. When he awakened he was in a strange place that seemed familiar but unfamiliar at the same time.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/New_Store_Steve.png/revision/latest?cb=20220618144437');
INSERT INTO Survivors VALUES('Bill Overbeck','Left Behind','Borrowed Time','Unbreakable','Hardened by years of experience, Bill Overbeck knows that survival rarely comes without sacrifice. No matter the cost, he’ll make sure his teammates live to fight another day. It wouldn’t be the first time he was left for dead.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/01/New_Store_Bill.png/revision/latest?cb=20220325045245');
INSERT INTO Survivors VALUES('Yoichi Asakawa','Parental Guidance','Empathic Connection','Boon: Dark Theory','A marine biologist scarred by the haunting memories of his past encounter with Sadako, Yoichi Asakawa has stared into the depths of evil. Blessed with paranormal psychic abilities of his own, his bravery and unwavering resolve makes him a valuable ally against even the darkest forces.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f3/New_Store_Yoichi.png/revision/latest?cb=20220618144736');
INSERT INTO Survivors VALUES('Yui Kimura','Lucky Break','Any Means Necessary','Breakout','Quick decisions are second nature to Yui Kimura, who lives the majority of her life at a breakneck pace. Whether riding an adrenaline high during a late-night street race or leading Killers on a long and winding chase, Yui finds a way to win by any means necessary.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0b/New_Store_Yui.png/revision/latest?cb=20220325045607');
INSERT INTO Survivors VALUES('Yun-Jin Lee','Fast Track','Smash Hit','Self-Preservation','What some call selfish, Yun-Jin Lee calls practical. She didn’t enter the music industry to make friends, though she can appreciate a little collaboration now and again. At the end of the day, she abides by an old classic: if you want something done right, do it yourself.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fd/New_Store_Yun-Jin.png/revision/latest?cb=20220325045618');
INSERT INTO Survivors VALUES('Zarina Kassir','Off the Record','Red Herring','For the People','Zarina Kassir stands determined to uncover the truth, regardless of any peril that might arise. A street-smart and thorough documentarian, she’s willing to put herself in harm’s way to achieve her goals -- especially if it means helping those in need.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/61/New_Store_Zarina.png/revision/latest?cb=20220325045629');
INSERT INTO Survivors VALUES('Élodie Rakoto','Appraisal','Deception','Power Struggle','Occult investigator Élodie Rakoto has seen first-hand that things are not always as they seem. The comforting rational explanation isn’t always correct, and there’s certainly no reasoning with these merciless Killers. Luckily, she’s got more than a few cunning tricks up her sleeve.
','https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/37/New_Store_Elodie.png/revision/latest?cb=20220325045411');

--NO ESTAN EN LA BASE DE DATOS

INSERT INTO Survivors VALUES('Gabriel Soma','Troubleshooter','Made for This','Scavenger',
'Gabriel Soma is a resourceful engineer, ready to make the most out of any situation.His personal Perks, TroubleshooterIconPerks troubleshooter, Made for ThisIconPerks madeForThis, and ScavengerIconPerks scavenger, help him see things during a Chase, gain Endurance after healing Survivors, and recharge his Toolbox.'
,'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/10/S37_storeBackground.png/revision/latest?cb=20230523203736');


INSERT INTO Survivors VALUES('Renato Lyra','Blood Rush','Teamwork: Collective Stealth','Background Player',
'Renato Lyra always keeps his eyes on the prize, and he expects the same from his teammates.His personal Perks, Blood RushIconPerks bloodRush, Teamwork: Collective StealthIconPerks teamworkCollectiveStealth, and Background PlayerIconPerks backgroundPlayer, allow him to move faster when near a chase, recover from Exhaustion instantly, and hide his and an allie''s Scratch Marks after healing.'
,'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/16/Store_Renato.png/revision/latest?cb=20230308040632');

INSERT INTO Survivors VALUES('Thalita Lyra','Friendly Competition','Teamwork: Power of Two','Cut Loose',
'Thalita Lyra has mastered the art of competitive flair, fighting kites with skill and flourish.
Her personal Perks, Friendly CompetitionIconPerks friendlyCompetition, Teamwork: Power of TwoIconPerks teamworkPowerOfTwo, and Cut LooseIconPerks cutLoose, allow her to perform a series of stealthy fast vaults, inspire faster repairs from teammates, and help allies move faster after they are healed by you.'
,'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/91/Store_Thalita.png/revision/latest?cb=20230308040648');


INSERT INTO Survivors VALUES('Vittorio Toscano','Potential Energy','Fogwise','Quick Gambit',
'Vittorio Toscano has endlessly wandered through The Fog, attempting to learn its secrets, for ages.
His personal Perks, Potential EnergyIconPerks potentialEnergy, FogwiseIconPerks fogwise, and Quick GambitIconPerks quickGambit, allow him to store Generator progress to use later, reveal the Killer''s location after a Great Skill Check, and give others a speed boost while repairing.'
,'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f2/Store_Vittorio.png/revision/latest?cb=20221122173820');




